language: python

python:
  - "2.7"

install:
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.1-src.tar.bz2 || wget https://bitbucket.org/pypy/pypy/downloads/pypy-5.1.1-src.tar.bz2
  - tar -xjf pypy-5.1.1-src.tar.bz2
  - mv pypy-5.1.1-src pypy
# command to run tests
script:
  - PYTHONPATH=$PYTHONPATH:pypy nosetests
  - PYTHONPATH=$PYTHONPATH:pypy ./som.sh -cp Smalltalk TestSuite/TestHarness.som
  - PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch src/targetsomstandalone.py
  - ./RTruffleSOM-no-jit -cp Smalltalk TestSuite/TestHarness.som
  #- PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch -Ojit src/targetsomstandalone.py
  #- ./RTruffleSOM-jit -cp Smalltalk TestSuite/TestHarness.som
