dist: xenial
language: python

python:
  - pypy

install:
 - travis_retry wget https://downloads.python.org/pypy/pypy2.7-v7.3.1-src.tar.bz2
 - tar -xjf pypy2.7-v7.3.1-src.tar.bz2
 - mv pypy2.7-v7.3.1-src pypy

script:
  - export SOM_INTERP=BC
  - PYTHONPATH=$PYTHONPATH:pypy nosetests
  - PYTHONPATH=$PYTHONPATH:pypy ./som.sh -cp Smalltalk TestSuite/TestHarness.som
  - PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch src/main-rpython.py
  - ./som-bc-interp -cp Smalltalk TestSuite/TestHarness.som
  #- PYTHONPATH=$PYTHONPATH:pypy pypy/rpython/bin/rpython --batch -Ojit src/main-rpython.py
  #- ./som-bc-jit -cp Smalltalk TestSuite/TestHarness.som
